import json

from channels.behavior_modification import get_medications_info, get_trainer_response
from channels.foster_questionnaire_responses import get_foster_notes_questionaire_info_reviewer_expanded
from channels.intake import get_intake_info
from channels.slack import get_slack_info
from parsers.behavior_modification_parser import parse_medication_info, parse_trainer_info
from parsers.foster_questionnaire_parser import parse_foster_questionnaire


def create_timeline(dog_name:str):
    pass